apiVersion: batch/v1
kind: CronJob 
metadata:
  name: mycronjob
spec:
  jobTemplate:
    metadata:
      name: mycronjob
    spec:
      template:
          spec:
            containers:
            - image: busybox
              name: mycronjob
              command: ['date']
              resources: {}
            restartPolicy: OnFailure
  schedule: '*/1 * * * *' 
